theme: jekyll-theme-cayman
title: This is going to be the Lacto-Veg Feed Stop!
name: The Lacto-Veg Feed Stop
description: Here we hope to get a blog going of recipes that are all lacto vegetarian and provide tips on how to make this diet exciting and fun to prepare.
